- name: Create prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Move binaries
  copy:
    remote_src: yes
    src: /opt/prometheus-2.52.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    mode: '0755'

- name: Copy config files
  copy:
    remote_src: yes
    src: /opt/prometheus-2.52.0.linux-amd64/promtool
    dest: /usr/local/bin/promtool
    mode: '0755'

- name: Copy prometheus.yml config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Create systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'

- name: Allow prometheus port 9090 through ufw
  ufw:
    rule: allow
    port: "9090"
    proto: tcp

- name: Reload and start prometheus
  systemd:
    daemon_reload: yes
    name: prometheus
    enabled: yes
    state: started