---

- name: Create postgres_exporter user
  user:
    name: postgres_exporter
    shell: /sbin/nologin

- name: Download postgres_exporter
  get_url:
    url: https://github.com/prometheus-community/postgres_exporter/releases/download/v0.15.0/postgres_exporter-0.15.0.linux-amd64.tar.gz
    dest: /tmp/postgres_exporter.tar.gz

- name: Extract postgres_exporter
  unarchive:
    src: /tmp/postgres_exporter.tar.gz
    dest: /opt/
    remote_src: yes

- name: Move binary
  copy:
    remote_src: yes
    src: /opt/postgres_exporter-0.15.0.linux-amd64/postgres_exporter
    dest: /usr/local/bin/postgres_exporter
    mode: '0755'

- name: Create systemd service for postgres_exporter
  template:
    src: postgres_exporter.service.j2
    dest: /etc/systemd/system/postgres_exporter.service
    mode: '0644'

- name: Allow postgres_exporter port 9187 through ufw
  ufw:
    rule: allow
    port: "9187"
    proto: tcp

- name: Reload systemd and start postgres_exporter
  systemd:
    daemon_reload: yes
    name: postgres_exporter
    enabled: yes
    state: started