global:
  resolve_timeout: 5m
  smtp_smarthost: ''
  smtp_from: ''
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  receiver: 'gmail-notifications'

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: ''
        from: ''
        smarthost: ''
        auth_username: ''
        auth_identity: ''
        auth_password: ''
        send_resolved: true