---

- name: Configure common settings
  hosts: all
  become: yes
  roles:
    - common
    - node_exporter

- name: Configure postgresql replication
  hosts: postgres_servers
  become: yes
  roles:
    - postgresql
    - postgres_exporter
  
- name: Configure monitoring stack
  hosts: monitoring_servers
  become: yes
  roles:
    - prometheus
    - grafana

